### PR TITLE
Clean up go.mod and remove redundant code

### PR DESCRIPTION
**Pull request by darenliang**

### CODE REVIEW

**Comment by George-lewis** [comment]
Thank you for your contribution. I usse RSRC in this project to generate the file that allows the executable to have an icon on Windows. Is it wise to remove it from the mod file?

**Comment by darenliang** [comment]
I don't think RSRC is used in the project directly given that it has the // indirect tag in go.mod.

It's a command line app and including it won't make a difference with the build.

I think it's best to document how the .syso file is generated though.

**Comment by darenliang** [comment]
I believe it is also possible to add the .syso file generation step into go generate.

**Comment by George-lewis** [comment]
Agreed, I will add the syso generation into a go:generate step. Will merge this now.

**Pull request merged**
